// web-fragments-demo/fragment-angular/src/app/app.ts
import { Component, signal, OnInit, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-root',
  imports: [],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App implements OnInit, OnDestroy {
  protected readonly count = signal(0);
  protected readonly receivedMessage = signal<string | null>(null);

  private bc: BroadcastChannel | null = null;
  private readonly FRAGMENT_NAME = 'Angular';

  ngOnInit() {
    // Set up broadcast channel listener
    this.bc = new BroadcastChannel('/fragment-events');
    this.bc.addEventListener('message', this.handleMessage.bind(this));
  }

  ngOnDestroy() {
    // Clean up broadcast channel
    if (this.bc) {
      this.bc.close();
      this.bc = null;
    }
  }

  private handleMessage(event: MessageEvent) {
    const { type, source } = event.data;

    if (type === 'fragment_broadcast') {
      if (source !== this.FRAGMENT_NAME) {
        this.receivedMessage.set(`Event received from ${source}`);
      } else {
        this.receivedMessage.set(null);
      }
    }
  }

  broadcastEvent() {
    if (this.bc) {
      this.receivedMessage.set(null);
      this.bc.postMessage({
        type: 'fragment_broadcast',
        source: this.FRAGMENT_NAME,
      });
    }
  }

  increment() {
    this.count.update((c) => c + 1);
  }

  decrement() {
    this.count.update((c) => c - 1);
  }
}

// web-fragments-demo/fragment-react/src/App.tsx
import React, { useState, useEffect } from 'react';
import './App.css';

function App() {
    const FRAGMENT_NAME = 'React';
    const [message, setMessage] = useState('Hello from React!');
    const [receivedMessage, setReceivedMessage] = useState<string | null>(null);
    const messages = [
        'Hello from React!',
        'Web Fragments are awesome!',
        'This is a micro-frontend!',
        'React Fragment here!',
        'Greetings from the component!',
    ];

    useEffect(() => {
        // Set up broadcast channel
        const bc = new BroadcastChannel('/fragment-events');

        const handleMessage = (event: MessageEvent) => {
            const { type, source } = event.data;
            if (type === 'fragment_broadcast') {
                if (source !== FRAGMENT_NAME) {
                    setReceivedMessage(`Event received from ${source}`);
                } else {
                    setReceivedMessage('');
                }
            }
        };

        bc.addEventListener('message', handleMessage);

        // Clean up on unmount
        return () => {
            bc.removeEventListener('message', handleMessage);
            bc.close();
        };
    }, []);

    const changeMessage = () => {
        const currentIndex = messages.indexOf(message);
        const nextIndex = (currentIndex + 1) % messages.length;
        setMessage(messages[nextIndex]);
    };

    const broadcastEvent = () => {
        const bc = new BroadcastChannel('/fragment-events');
        bc.postMessage({
            type: 'fragment_broadcast',
            source: FRAGMENT_NAME,
        });
        bc.close();
    };

    return (
        <div className="greeting">
            <h3>{message}</h3>
            <button onClick={changeMessage}>Change Message</button>
            {/* <div className="broadcast-section">
                <button onClick={broadcastEvent}>Broadcast Event</button>
                {receivedMessage && (
                    <p className="message">{receivedMessage}</p>
                )}
            </div> */}
        </div>
    );
}

export default App;
